### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by circumpolaire** [jespino/inkscape-export-layers#1]
Hi,
I'm teatcher of geography. I'm very interesting by your extension for Inkscape. But it doesn't export, nothing... Please could you write a tutorial for beginner ?
Thanks a lot
Circumpolaire

**Comment by jespino** [comment]
The readme file explain the normal behavior. So if it's not working can be nice know why and fix the explanation in the readme file. Maybe a problem with the dependencies, you need ImageMagick to generate the JPEG files.

Can you try to generate the exports in PNG format? Are you using the [export] and [fixed] strings in your layers? If you prefer it you can askme directly by Email (jespinog@gmail.com).

**Comment by jespino** [comment]
The problem was related with the case sensitive of fixed/export strings in the layers. I have changed it to case insesitive.

One more time thanks! :sparkles:

**Comment by circumpolaire** [comment]
Thanks you !


2016-06-23 17:47 GMT+02:00 Jesús Espino <notifications@github.com>:

**Comment by circumpolaire** [comment]
But it doesn't work. I send what your extension write when i try to export.
Does it work with my map with you ?

Laurent

2016-06-23 17:58 GMT+02:00 Lolo Circumpolaire <circumpolaire@gmail.com>:

> Thanks you !
>
>
> 2016-06-23 17:47 GMT+02:00 Jesús Espino <notifications@github.com>:
>
>> Closed #1 <https://github.com/jespino/inkscape-export-layers/issues/1>.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/jespino/inkscape-export-layers/issues/1#event-702081940>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ATLicUHHacdlqoCZ31JKqCRmIZLVEQW5ks5qOqp4gaJpZM4I86Cr>
>> .
>>
>
>

Try 1 :
Traceback (most recent call last):
  File "export_layers.py", line 107, in <module>
    _main()
  File "export_layers.py", line 103, in _main
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "export_layers.py", line 39, in effect
    self.exportToPng(layer_dest_svg_path, layer_dest_png_path)
  File "export_layers.py", line 92, in exportToPng
    p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 633, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 842, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 77: ordinal not in range(128)

Try 2 :
Traceback (most recent call last):
  File "export_layers.py", line 107, in <module>
    _main()
  File "export_layers.py", line 103, in _main
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "export_layers.py", line 39, in effect
    self.exportToPng(layer_dest_svg_path, layer_dest_png_path)
  File "export_layers.py", line 92, in exportToPng
    p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 633, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 842, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 86: ordinal not in range(128)

Try 3 :
Traceback (most recent call last):
  File "export_layers.py", line 107, in <module>
    _main()
  File "export_layers.py", line 103, in _main
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "export_layers.py", line 39, in effect
    self.exportToPng(layer_dest_svg_path, layer_dest_png_path)
  File "export_layers.py", line 92, in exportToPng
    p = subprocess.Popen(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 633, in __init__
    errread, errwrite)
  File "C:\Program Files\Inkscape\python\Lib\subprocess.py", line 842, in _execute_child
    startupinfo)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 86: ordinal not in range(128)

**Comment by jespino** [comment]
Looks like an encoding problem, it doesn't happens in my Linux machine, I have forced the encoding of command as utf-8 string. Can you pull the changes and try again?

**Comment by circumpolaire** [comment]
Hi Jesus
I destroyed "encoding uft-8" in the "export_layers.inx" file. Then it will
work. But it doesn't accept french accent in the title of layers (for
exemple Axes ferrés). Then the addon export in svg ! If i change the tittle
it will be good. As you can see. But there are a second problem : when i
choice jpeg, the background of the image is black. In PNG, there aren't
background.
[image: Images intégrées 1]
Thanks for your addon
Laurent

2016-06-23 18:23 GMT+02:00 Jesús Espino <notifications@github.com>:

**Comment by circumpolaire** [comment]
HI Jesus,
After that i tryed an another thing : i keep your exact file
"export_layers.inx"  but i converted it in uft-8 witn Notepad ++
(before in uft-8(withoutBOM)).
And it will be good except the bacground of jpeg and the french accent in
title of layers.
Laurent

2016-06-24 17:19 GMT+02:00 Lolo Circumpolaire <circumpolaire@gmail.com>:
