### ISSUE TITLE
Windows 10 error

### ISSUE THREAD

**Issue by hernandoramos** [jespino/inkscape-export-layers#16]
Hi
I'm getting this error when i ty to use the exporter

```
Traceback (most recent call last):
  File "export_layers.py", line 112, in <module>
    _main()
  File "export_layers.py", line 108, in _main
    e.affect()
  File "inkex.py", line 283, in affect
    self.effect()
  File "export_layers.py", line 39, in effect
    self.export_layers(layer_dest_svg_path, show_layer_ids)
  File "export_layers.py", line 66, in export_layers
    doc.write(dest)
  File "src/lxml/etree.pyx", line 2037, in lxml.etree._ElementTree.write
  File "src/lxml/serializer.pxi", line 721, in lxml.etree._tofilelike
  File "src/lxml/serializer.pxi", line 780, in lxml.etree._create_output_buffer
  File "src/lxml/serializer.pxi", line 770, in lxml.etree._create_output_buffer
IOError: [Errno 13] Permission denied
```

All layers I want to export are labeled [export] and I try to export to different paths in different drives without any luck
Is there any chance to get this working?
Thanks

**Comment by dmitry-t** [comment]
Isn't it #9?
There is a PR with a solution - #10, but it's been waiting for a merge for quite a long time.
