### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by arduinoNube** [jespino/inkscape-export-layers#6]
Hi!  I love the concept for your extension.  I downloaded the most recent version and got this error on export:

`Traceback (most recent call last):
  File "export_layers.py", line 112, in <module>
    _main()
  File "export_layers.py", line 108, in _main
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "export_layers.py", line 39, in effect
    self.export_layers(layer_dest_svg_path, show_layer_ids)
  File "export_layers.py", line 66, in export_layers
    doc.write(dest)
  File "lxml.etree.pyx", line 1685, in lxml.etree._ElementTree.write (src/lxml/lxml.etree.c:40410)
  File "serializer.pxi", line 407, in lxml.etree._tofilelike (src/lxml/lxml.etree.c:81512)
IOError: [Errno 13] Permission denied
`
I'm on a windows 7 professional machine with Inkscape 0.91 r13725.

Any suggestions?  Thanks!

**Comment by jespino** [comment]
I'm not sure, but looks like you don't have permissions to write the file in the destination.

**Comment by arduinoNube** [comment]
You're right. I don't think Windows gives applications write access to the Program Files directory.  Looks like I'll need to submit a bug to the inkex.py extension people to see what's up.

**Comment by xtempore** [comment]
Did you ever get a reply? I'm having the same problem. Tried all sorts of places to export to, but always "permission denied"
