### ISSUE TITLE
permission denied

### ISSUE THREAD

**Issue by butterflyx** [jespino/inkscape-export-layers#8]
If I try to export, the script aborts with this trace:

`Traceback (most recent call last):
  File "export_layers.py", line 112, in <module>
    _main()
  File "export_layers.py", line 108, in _main
    e.affect()
  File "C:\Program Files\Inkscape\share\extensions\inkex.py", line 268, in affect
    self.effect()
  File "export_layers.py", line 39, in effect
    self.export_layers(layer_dest_svg_path, show_layer_ids)
  File "export_layers.py", line 66, in export_layers
    doc.write(dest)
  File "lxml.etree.pyx", line 1685, in lxml.etree._ElementTree.write (src/lxml/lxml.etree.c:40410)
  File "serializer.pxi", line 407, in lxml.etree._tofilelike (src/lxml/lxml.etree.c:81512)
IOError: [Errno 13] Permission denied`

Same result for any dir I tried.

I used multiple and nested layers in the image. 

Thank you for any support.

(Win10 and Inkscape 0.91 r13725)

**Comment by butterflyx** [comment]
Dup in closed issues found
